name: 'Build and autograde'

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  Build:
    name: 'Build Log'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout assignment
        uses: actions/checkout@v3.0.2
      - name: Configure Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build assignment and run tests
        run: mvn -V -ntp clean verify -Dmaven.test.failure.ignore=true --file pom.xml
      - name: Autograde code (tests and analysis)
        uses: uhafner/autograding-github-action@v1.7.0
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_SHA: ${{github.event.pull_request.head.sha}}
          CONFIG: >
            {
              "analysis": {
                "maxScore": 100,
                "errorImpact": -5,
                "highImpact": -3,
                "normalImpact": -2,
                "lowImpact": -1
              },
              "tests": {
                "maxScore": 100,
                "passedImpact": 0,
                "failureImpact": -5,
                "skippedImpact": -1
              },
              "coverage": {
                "maxScore": 100,
                "coveredPercentageImpact": 0,
                "missedPercentageImpact": -1
              },
              "pit": {
                "maxScore": 100,
                "detectedImpact": 0,
                "undetectedImpact": 0,
                "detectedPercentageImpact": 0,
                "undetectedPercentageImpact": -1
              }
            }
